structure_vqvae:
  name: SepVQVAE_DDP_body_hands
  data: mocap
  body:
    joint_indexes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 93, 94, 104, 105, 313, 314, 324, 325, 592, 593, 594, 638, 639, 640, 694] #24(with root trans)
    levels: 1
    downs_t: [3, ]
    strides_t: [2, ]
    emb_width: 512
    l_bins: 512
    l_mu: 0.95
    commit: 0.02
    hvqvae_multipliers: [1, ]
    width: 512
    depth: 3
    m_conv: 1.0
    dilation_growth_rate: 3
    sample_length: 120
    use_bottleneck: True
    bottleneck_type: 'rqvae'
    rq_num_quantizers: 4
    joint_channel: 3
    vel: 1
    acc: 1
    reg: 0
    vqvae_reverse_decoder_dilation: True
    weight: 3
    encoder_transformer: True
    decoder_transformer: True
    transformer_head: 4
    transformer_depth: 3
    transformer_dropout: 0
    has_after_decoder_transformer: False
    after_d_transformer_head: 4
    after_d_transformer_depth: 2
    after_d_transformer_dropout: 0
  hands:
    joint_indexes: [107, 108, 109, 144, 145, 146, 180, 181, 182, 210, 211, 212, 247, 248, 249, 327,
                    328, 329, 364, 365, 366, 400, 401, 402, 430, 431, 432, 467, 468, 469]
    levels: 1
    downs_t: [3, ]
    strides_t: [2, ]
    emb_width: 512
    l_bins: 512
    l_mu: 0.95
    commit: 0.02
    hvqvae_multipliers: [1, ]
    width: 512
    depth: 3
    m_conv: 1.0
    dilation_growth_rate: 3
    sample_length: 240
    use_bottleneck: True
    bottleneck_type: 'rqvae'
    rq_num_quantizers: 4
    joint_channel: 3
    vel: 1
    acc: 1
    reg: 0
    vqvae_reverse_decoder_dilation: True
    weight: 2
    encoder_transformer: True
    decoder_transformer: True
    transformer_head: 4
    transformer_depth: 2
    transformer_dropout: 0
    has_after_decoder_transformer: False
    after_d_transformer_head: 4
    after_d_transformer_depth: 2
    after_d_transformer_dropout: 0

  root_loss_weight: 0
  use_bottleneck: True
  joint_channel: 3
  joint_num: 696
  l_bins: 512

structure_gpt:
  name: CrossCondGPT2_2part
  block_size: 14
  n_music: 437
  n_music_emb: 768
  base:
    embd_pdrop: 0.1
    resid_pdrop: 0.1
    attn_pdrop: 0.1
    vocab_size_body: 512
    vocab_size_hands: 512
    block_size: 14
    n_layer: 6
    n_head: 12
    n_embd: 768
    n_music: 437
    n_music_emb: 768
    n_modality: 3  # number of required modalities: x vqvaes plus 1 audio
  head:
    embd_pdrop: 0.1
    resid_pdrop: 0.1
    attn_pdrop: 0.1
    vocab_size: 512
    block_size: 14
    n_layer: 6
    n_head: 12
    n_embd: 768
    vocab_size_body: 512
    vocab_size_hands: 512
    n_music: 437
    n_music_emb: 768
    n_modality: 3


data:
  name: mocap
  dir: Data/JIYI_processed
  test_files: ["CAREER_1_4_001_bar_1", "GAME_7_13_001_bar_1", "HEALTH_7_11_001_bar_1", "RELATIONSHIP_12_17_001_bar_1", "CAREER_1_4_001_mirror_bar_1", "GAME_7_13_001_mirror_bar_1", "HEALTH_7_11_001_mirror_bar_1", "RELATIONSHIP_12_17_001_mirror_bar_1"]
  seq_len_train: 120  
  stride_train: 8 
  seq_len_test: 2400 
  stride_test: 2400 
  samples_per_test: 1  
  ds_rate: 8 

optimizer:
  type: AdamW
  kwargs:
    lr: 0.0005
#    betas: [0.5, 0.999]
    betas: [0.9, 0.999]
    weight_decay: 0
  schedular_kwargs:
    milestones: [80, 150, 220]
    gamma: 0.4

exp_name: train_gpt_jiyi_audio_causal_cross
log_name: motion_gpt_1
need_not_train_data: 0
need_not_test_data: 1

seed: 42
batch_size: 256
epochs: 200
save_per_epochs: 10
eval_per_epochs: 10
log_per_updates: 1
tensorboard: True
cuda: True
global_vel: False

vqvae_weight: 'Experiment/train_rqvae_jiyi/jiyi_rqvae_20251028_20251029171426/Checkpoint/epoch_200.pt'

init_weight: ''
